PL__MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL__MVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PL__MVC/Controllers/LibroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;

namespace PL__MVC.Controllers
{
    public class LibroController : Controller
    {
        // GET: Libro
        [HttpGet]
        public ActionResult GetAll()
        {
            Ml.Result result = Bl.Libro.GetAllEF();
            Ml.Libro libro = new Ml.Libro();
            if (result.Correct)
            {
                libro.Libros = result.Objects;
            }
            else
            {
                ViewBag.Message = "Ocurrio un error, no se pueden mostar los registro ";
            }
            return View(libro);
        }
        [HttpGet]
        public ActionResult Form(int? IdLibro)
        {
            Ml.Libro libro = new Ml.Libro();
            Ml.Result resulrol = new Ml.Result();
            libro.Autor = new Ml.Autor();
            libro.Editorial = new Ml.Editorial();
            libro.Genero = new Ml.Genero();

            Ml.Result resultautor = Bl.Autor.GetAllEF();
            Ml.Result resulteditorial = Bl.Editorial.GetAllEF();
            Ml.Result resultgenero = Bl.Genero.GetAllEF();

            if (IdLibro == null)
            {

                libro.Autor.Autores = resultautor.Objects;
                libro.Editorial.Editoriales = resulteditorial.Objects;
                libro.Genero.Generos= resultgenero.Objects;
                
                return View(libro);
            }

            else
            {
                Ml.Result result = Bl.Libro.GetByIdEF(IdLibro.Value);

                if (result.Correct)
                {
                    libro = (Ml.Libro)result.Object;
                    
                    libro.Autor.Autores = resultautor.Objects;
                    libro.Editorial.Editoriales = resulteditorial.Objects;
                    libro.Genero.Generos = resultgenero.Objects;


                }
                else
                {
                    ViewBag.Message = "Ocurrio un error al consultar al usuario seleccionado";
                }
                return View(libro);
            }
        }

        [HttpPost]
        public ActionResult Form(Ml.Libro libro)
        {

            if (libro.IdLibro == 0)
            {
                //add
                Ml.Result result = Bl.Libro.AddEF(libro);

                if (result.Correct)
                {
                    libro = (Ml.Libro)result.Object;
                    ViewBag.Mensaje = "Libro guardado exitosamente";

                }
                else
                {
                    ViewBag.Mensaje = "Ocurrio un error al agregar el libro";
                }
            }
            else
            {
                //update
                Ml.Result result = Bl.Libro.UpdateEF(libro);

                if (result.Correct)
                {
                    libro = (Ml.Libro)result.Object;
                    ViewBag.Mensaje = "libro Actualizado Correctamente";
                }
                else
                {
                    ViewBag.Mensaje = "Ocurrio un error El libro no se pudo actualizar";
                }

            }

            return PartialView("Modal");

        }

        public ActionResult Delete(int IdLibro)
        {

            Ml.Result result = new Ml.Result();
            result = Bl.Libro.DeleteEF(IdLibro);

            if (result.Correct)
            {
                ViewBag.Mensaje = "Se elimino el registro";
            }
            return PartialView("Modal");
        }
    }
}

PL__MVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

PL__MVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PL__MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

PL__MVC/Views/Libro/Form.cshtml
@model Ml.Libro
@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Form</h2>
<h2>Form</h2>
<div class="row">
    <div class="col-md-12">
        @using (Html.BeginForm("Form", "Libro", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
        <div class="form-horizontal">

            <div class="form-group">

                <div class="col-md-3">

                    @Html.LabelFor(model => model.IdLibro, new { @class = "hidden" })

                    @Html.TextBoxFor(model => model.IdLibro, new { @class = "hidden form-control" })

                    @Html.ValidationMessageFor(model => model.IdLibro)

                </div>

            </div>
            <div class="form-group">
                <div class="col-md-3">
                    @Html.LabelFor(model => model.Nombre)
                    @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @id = "txtNombre" })
                    @Html.ValidationMessageFor(model => model.Nombre)
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3">
                    @Html.LabelFor(model => model.NumeroDePaginas)
                    @Html.TextBoxFor(model => model.NumeroDePaginas, new { @class = "form-control", @id = "txtpag" })
                    @Html.ValidationMessageFor(model => model.NumeroDePaginas)
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3">
                    @Html.LabelFor(model => model.FechaPublicacion)
                    @Html.TextBoxFor(model => model.FechaPublicacion, new { @class = "form-control", @id = "txtNombre" })
                    @Html.ValidationMessageFor(model => model.FechaPublicacion)
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3">
                    @Html.LabelFor(model => model.Edicion)
                    @Html.TextBoxFor(model => model.Edicion, new { @class = "form-control", @id = "txtNombre" })
                    @Html.ValidationMessageFor(model => model.Edicion)
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3">
                    @Html.LabelFor(model => model.Autor.IdAutor)

                    @Html.DropDownListFor(model => model.Autor.IdAutor, new SelectList(Model.Autor.Autores, "IdAutor", "Nombre"), "Selecciona una opción", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Autor.IdAutor)
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3">
                    @Html.LabelFor(model => model.Editorial.IdEditorial)

                    @Html.DropDownListFor(model => model.Editorial.IdEditorial, new SelectList(Model.Editorial.Editoriales, "IdEditorial", "Nombre"), "Selecciona una opción", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Editorial.IdEditorial)
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3">
                    @Html.LabelFor(model => model.Genero.IdGenero)

                    @Html.DropDownListFor(model => model.Genero.IdGenero, new SelectList(Model.Genero.Generos, "IdGenero", "Nombre"), "Selecciona una opción", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Genero.IdGenero)
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3">
                    <input type="submit" value="Guardar" class="btn btn-success" />
                    @Html.ActionLink("Regresar", "GetAll", "Libros", htmlAttributes: new { @class = "btn btn-success" })
                </div>
            </div>


        </div>

                }
            </div>
        </div>
    </div>

PL__MVC/Views/Libro/GetAll.cshtml
@model Ml.Libro
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>GetAll</h2>

<div class="container">


    <div class="row">
        <div style="float:right">
            @Html.ActionLink("+", "Form", "Libro", htmlAttributes: new { @class = "btn btn-success" })
        </div>
    </div>

    <hr />
    <div class="row">
        <table class="tablcenter table-hover table-bordered table-responsive ">

            <thead>
                <tr>
                    <th>Editar</th>

                    <th>Nombre</th>
                    <th>Numero de paginas</th>
                    <th>Fecha de publicacion </th>
                    <th>Edicion</th>
                    <th>Autor</th>
                    <th>Editorial</th>
                    <th>Genero</th>

                    <th>Eliminar</th>
                </tr>
            </thead>
            <tbody>
                @foreach (Ml.Libro libro in Model.Libros)
                {
                    <tr>
                        <td class="text-center"><a class="btn btn-warning glyphicon glyphicon-edit" href="@Url.Action("Form", "Libro", new { IdLibro = libro.IdLibro })"></a></td>
                        <td class="hidden">@libro.IdLibro</td>
                        <td>@libro.Nombre </td>
                        <td> @libro.NumeroDePaginas</td>
                        <td> @libro.FechaPublicacion</td>
                        <td> @libro.Edicion</td>
                        <td> @libro.Autor.Nombre</td>
                        <td> @libro.Editorial.Nombre</td>
                        <td> @libro.Genero.Nombre</td>

                        <td class="text-center"><a class="btn btn-danger glyphicon glyphicon-trash" href="@Url.Action("Delete", "Libro", new { IdLibro = libro.IdLibro })" onclick="return confirm('Estas seguro que deseas eliminar este registro?');"></a></td>
                    </tr>

                }
            </tbody>
        </table>
    </div>
</div>

PL__MVC/Views/Libro/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Mensaje</h5>
            </div>
            <div class="modal-footer">

                @Html.ActionLink("Ok", "GetAll", "Usuario", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>

PL__MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Libros", "GetAll", "Libro")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>